### PR TITLE
Custom image for scratchable area

### PR DESCRIPTION
**Pull request by ChathuraHettiarachchi**
Added attributes to change scratchable area. User only need to add
app:customScrach on xml to change overlay image. user can pass drawable.

### CODE REVIEW

**Comment by burakkoray** [comment]
Hi
Have you merged this enhancement ?
If you have any chance to do that please could you make it ?

**Comment by sharish** [comment]
The ScratchView was designed with the idea of real scratch card in software world. Having the customised version of scratch pattern image though techinically a very good enhancement, I'm afraid to merge as it takes away feel of scratch card to "erasing an image placed on another". Moreover I would like to keep this repo much simpler without customisations. This pull request will not be merged for the above reasons. If you are still interested with the customisation, you can refer the forked repo - https://github.com/ChathuraHettiarachchi/ScratchView.

Thanks,
Harish

**Comment by burakkoray** [comment]
Thanks Harish for this great project  . I forked and used this project
Many thanks...

**Comment by atulac** [comment]
> The ScratchView was designed with the idea of real scratch card in software world. Having the customised version of scratch pattern image though techinically a very good enhancement, I'm afraid to merge as it takes away feel of scratch card to "erasing an image placed on another". Moreover I would like to keep this repo much simpler without customisations. This pull request will not be merged for the above reasons. If you are still interested with the customisation, you can refer the forked repo - https://github.com/ChathuraHettiarachchi/ScratchView.
> 
> Thanks,
> Harish

Just an opinion and a request:
With Google Pay and PhonePe kind of giants building scratch cards with a custom interface, I think it becomes imperative to understand it's need. Repo deserves an upgrade. It's your call anyways.

Thanks

**Pull request closed without merging**
